INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'No Way Up', 'Characters from different backgrounds are thrown together when the plane they''re travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.', '/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Godzilla x Kong: The New Empire', 'Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.', '/bQ2ywkchIiaKLSEaMrcT6e29f91.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Rebel Moon - Part Two: The Scargiver', 'The rebels gear up for battle against the ruthless forces of the Motherworld as unbreakable bonds are forged, heroes emerge — and legends are made.', '/cxevDYdeFkiixRShbObdwAHBZry.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Dune: Part Two', 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.', '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Kung Fu Panda 4', 'Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.', '/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Ape vs. Mecha Ape', 'Recognizing the destructive power of its captive giant Ape, the military makes its own battle-ready A.I., Mecha Ape. But its first practical test goes horribly wrong, leaving the military no choice but to release the imprisoned giant ape to stop the colossal robot before it destroys downtown Chicago.', '/dJaIw8OgACelojyV6YuVsOhtTLO.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Immaculate', 'An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.', '/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Spitfire Over Berlin', 'August 1944. With the American Eighth Air Force poised to strike over Nazi Germany, British Intelligence learns that they could be flying into a deadly trap. With only hours to spare, Flight Lieutenant Edward Barnes must fly a life and death mission over Berlin in his unarmed Spitfire to obtain photographic evidence and save the lives of 1200 men.', '/xtPPOPTad1qopK6uDe3VlYUa22o.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Three Musketeers: Milady', 'D''Artagnan, on a quest to rescue the abducted Constance, runs into the mysterious Milady de Winter again. The tension between the Catholics and the Protestants finally escalates, as the king declares war — forcing the now four musketeers into battle. But as the war goes on, they are tested physically, mentally and emotionally.', '/rtosxP5sXuoRFPH4sVbMccLIPiV.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Arthur the King', 'Over the course of ten days and 435 miles, an unbreakable bond is forged between pro adventure racer Michael Light and a scrappy street dog companion dubbed Arthur. As the team is pushed to their outer limits of endurance in the race, Arthur redefines what victory, loyalty and friendship truly mean.', '/gxVcBc4VM0kAg9wX4HVg6KJHG46.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Damaged', 'A Chicago detective travels to Scotland after an emerging serial killer’s crimes match those that he investigated five years earlier, one of which was the crime scene of his murdered girlfriend.', '/tMO0YLXgJZBnIAjoTSz26zE33YN.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Alienoid', 'Gurus in the late Goryeo dynasty try to obtain a fabled, holy sword, and humans in 2022 hunt down an alien prisoner that is locked in a human''s body. The two parties cross paths when a time-traveling portal opens up.', '/8QVDXDiOGHRcAD4oM6MXjE0osSj.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Madame Web', 'Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.', '/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Fighter', 'Top IAF aviators come together in the face of imminent danger, to form Air Dragons. Fighter unfolds their camaraderie, brotherhood and battles, internal and external.', '/zDZowwb9GZGEctAu2PCpjiPQAMM.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Road House', 'Ex-UFC fighter Dalton takes a job as a bouncer at a Florida Keys roadhouse, only to discover that this paradise is not all it seems.', '/bXi6IQiQDHD00JFio5ZSZOeRSBh.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Migration', 'After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.', '/ldfCF9RhR40mppkzmftxapaHeTo.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Justice League: Crisis on Infinite Earths Part Two', 'An endless army of shadow demons bent on the destruction of all reality swarms over our world and all parallel Earths! The only thing opposing them is the mightiest team of metahumans ever assembled. But not even the combined power of Superman, Batman, Wonder Woman, Green Lantern and all their fellow superheroes can slow down the onslaught of this invincible horde. What mysterious force is driving them? And how do the long-buried secrets of the Monitor and Supergirl threaten to crush our last defense?', '/g8ak4QAGLZpqMs3CpnFHWWfIzJQ.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Wages of Fear', 'When an explosion at an oil well threatens hundreds of lives, a crack team is called upon to make a deadly desert crossing with nitroglycerine in tow.', '/jFK2ZLQUzo9pea0jfMCHDfvWsx7.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Civil War', 'In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.', '/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg', 5.00, 1, 'undefined');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Breathe', 'Air-supply is scarce in the near future, forcing a mother and daughter to fight for survival when two strangers arrive desperate for an oxygenated haven.', '/wTW2t8ocWDlHns8I7vQxuqkyK58.jpg', 5.00, 1, 'undefined');