INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'No Way Up', 'Characters from different backgrounds are thrown together when the plane they''re travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.', '/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Godzilla x Kong: The New Empire', 'Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.', '/bQ2ywkchIiaKLSEaMrcT6e29f91.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Rebel Moon - Part Two: The Scargiver', 'The rebels gear up for battle against the ruthless forces of the Motherworld as unbreakable bonds are forged, heroes emerge — and legends are made.', '/cxevDYdeFkiixRShbObdwAHBZry.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Dune: Part Two', 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.', '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Kung Fu Panda 4', 'Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.', '/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg', 5.00, 1, 'Animation');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Ape vs. Mecha Ape', 'Recognizing the destructive power of its captive giant Ape, the military makes its own battle-ready A.I., Mecha Ape. But its first practical test goes horribly wrong, leaving the military no choice but to release the imprisoned giant ape to stop the colossal robot before it destroys downtown Chicago.', '/dJaIw8OgACelojyV6YuVsOhtTLO.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Immaculate', 'An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.', '/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Spitfire Over Berlin', 'August 1944. With the American Eighth Air Force poised to strike over Nazi Germany, British Intelligence learns that they could be flying into a deadly trap. With only hours to spare, Flight Lieutenant Edward Barnes must fly a life and death mission over Berlin in his unarmed Spitfire to obtain photographic evidence and save the lives of 1200 men.', '/xtPPOPTad1qopK6uDe3VlYUa22o.jpg', 5.00, 1, 'War');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Three Musketeers: Milady', 'D''Artagnan, on a quest to rescue the abducted Constance, runs into the mysterious Milady de Winter again. The tension between the Catholics and the Protestants finally escalates, as the king declares war — forcing the now four musketeers into battle. But as the war goes on, they are tested physically, mentally and emotionally.', '/rtosxP5sXuoRFPH4sVbMccLIPiV.jpg', 5.00, 1, 'Adventure');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Arthur the King', 'Over the course of ten days and 435 miles, an unbreakable bond is forged between pro adventure racer Michael Light and a scrappy street dog companion dubbed Arthur. As the team is pushed to their outer limits of endurance in the race, Arthur redefines what victory, loyalty and friendship truly mean.', '/gxVcBc4VM0kAg9wX4HVg6KJHG46.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Damaged', 'A Chicago detective travels to Scotland after an emerging serial killer’s crimes match those that he investigated five years earlier, one of which was the crime scene of his murdered girlfriend.', '/tMO0YLXgJZBnIAjoTSz26zE33YN.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Alienoid', 'Gurus in the late Goryeo dynasty try to obtain a fabled, holy sword, and humans in 2022 hunt down an alien prisoner that is locked in a human''s body. The two parties cross paths when a time-traveling portal opens up.', '/8QVDXDiOGHRcAD4oM6MXjE0osSj.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Madame Web', 'Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.', '/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Fighter', 'Top IAF aviators come together in the face of imminent danger, to form Air Dragons. Fighter unfolds their camaraderie, brotherhood and battles, internal and external.', '/zDZowwb9GZGEctAu2PCpjiPQAMM.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Road House', 'Ex-UFC fighter Dalton takes a job as a bouncer at a Florida Keys roadhouse, only to discover that this paradise is not all it seems.', '/bXi6IQiQDHD00JFio5ZSZOeRSBh.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Migration', 'After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.', '/ldfCF9RhR40mppkzmftxapaHeTo.jpg', 5.00, 1, 'Animation');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Justice League: Crisis on Infinite Earths Part Two', 'An endless army of shadow demons bent on the destruction of all reality swarms over our world and all parallel Earths! The only thing opposing them is the mightiest team of metahumans ever assembled. But not even the combined power of Superman, Batman, Wonder Woman, Green Lantern and all their fellow superheroes can slow down the onslaught of this invincible horde. What mysterious force is driving them? And how do the long-buried secrets of the Monitor and Supergirl threaten to crush our last defense?', '/g8ak4QAGLZpqMs3CpnFHWWfIzJQ.jpg', 5.00, 1, 'Animation');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Wages of Fear', 'When an explosion at an oil well threatens hundreds of lives, a crack team is called upon to make a deadly desert crossing with nitroglycerine in tow.', '/jFK2ZLQUzo9pea0jfMCHDfvWsx7.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Civil War', 'In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.', '/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg', 5.00, 1, 'War');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Breathe', 'Air-supply is scarce in the near future, forcing a mother and daughter to fight for survival when two strangers arrive desperate for an oxygenated haven.', '/wTW2t8ocWDlHns8I7vQxuqkyK58.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Breathe', 'Air-supply is scarce in the near future, forcing a mother and daughter to fight for survival when two strangers arrive desperate for an oxygenated haven.', '/wTW2t8ocWDlHns8I7vQxuqkyK58.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Late Night with the Devil', 'A live broadcast of a late-night talk show in 1977 goes horribly wrong, unleashing evil into the nation''s living rooms.', '/u3YQJctMzFN2wAvnkmXy41bXhFv.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Oppenheimer', 'The story of J. Robert Oppenheimer''s role in the development of the atomic bomb during World War II.', '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Justice League: Crisis on Infinite Earths Part One', 'Death is coming. Worse than death: oblivion. Not just for our Earth, but for everyone, everywhere, in every universe! Against this ultimate destruction, the mysterious Monitor has gathered the greatest team of Super Heroes ever assembled. But what can the combined might of Superman, Wonder Woman, Batman, The Flash, Green Lantern and hundreds of Super Heroes from multiple Earths even do to save all of reality from an unstoppable antimatter armageddon?!', '/zR6C66EDklgTPLHRSmmMt5878MR.jpg', 5.00, 1, 'Animation');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Outsource', 'A police chief hires an old friend, who is an international spy, to help him search for a wanted suspect in the Philippines. When the chief dies, all evidence points towards the spy, and he must go to extremes to defend himself.', '/zIAF0UXtCJTJOYNYWiBfyifaaOi.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Kingdom of the Planet of the Apes', 'Several generations in the future following Caesar''s reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all that he has known about the past and to make choices that will define a future for apes and humans alike.', '/gKkl37BQuKTanygYQG1pyYgLVgf.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Dune', 'Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet''s exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity''s greatest potential-only those who can conquer their fear will survive.', '/d5NXSklXo0qyIYkgV94XAgMIckC.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Fast X', 'Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they''ve ever faced: A terrifying threat emerging from the shadows of the past who''s fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.', '/fiVW06jE7z9YnO4trhaMEdclSiC.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Woody Woodpecker Goes to Camp', 'After getting kicked out of the forest, Woody thinks he''s found a forever home at Camp Woo Hoo — until an inspector threatens to shut down the camp.', '/mMnzNYvpqLLLdgF5TMmXfuy6wzx.jpg', 5.00, 1, 'Family');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Hard Hit', 'On his way to work, a bank manager receives an anonymous call claiming there''s a bomb under his car seat, and if anyone exits the car, it will explode unless he can pay a ransom.', '/y2Aimt8isimtigec3e4kB2G9FMR.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'After the Pandemic', 'Set in a post-apocalyptic world where a global airborne pandemic has wiped out 90% of the Earth''s population and only the young and immune have endured as scavengers. For Ellie and Quinn, the daily challenges to stay alive are compounded when they become hunted by the merciless Stalkers.', '/p1LbrdJ53dGfEhRopG71akfzOVu.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Elevator Game', 'Follows socially awkward teenager Ryan, who discovers that the night his sister disappeared she had played ‘The Elevator Game’ — a ritual conducted in an elevator in which players attempt to travel to another dimension using a set of rules that can be found online. Ignoring warnings, he resolves to follow and find her.', '/a4Zb13jow8RqJkYFgCUSdmzJCWq.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Damsel', 'A young woman''s marriage to a charming prince turns into a fierce fight for survival when she''s offered up as a sacrifice to a fire-breathing dragon.', '/AgHbB9DCE9aE57zkHjSmseszh6e.jpg', 5.00, 1, 'Fantasy');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Deadpool', 'The origin story of former Special Forces operative turned mercenary Wade Wilson, who, after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.', '/fSRb7vyIP8rQpL0I47P3qUsEKX3.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Ghostbusters', 'Following a ghost invasion of Manhattan, paranormal enthusiasts Erin Gilbert and Abby Yates, nuclear engineer Jillian Holtzmann, and subway worker Patty Tolan band together to stop the otherworldly threat.', '/wJmWliwXIgZOCCVOcGRBhce7xPS.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Tenet', 'Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.', '/k68nPLbIST6NP96JmTxmZijEvCA.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'X', 'In 1979, a group of young filmmakers set out to make an adult film in rural Texas, but when their reclusive, elderly hosts catch them in the act, the cast find themselves fighting for their lives.', '/woTQx9Q4b8aO13jR9dsj8C9JESy.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Batman', 'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.', '/74xTEgt7R36Fpooo50r9T25onhq.jpg', 5.00, 1, 'Crime');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Joker', 'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.', '/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg', 5.00, 1, 'Crime');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Captain Marvel', 'The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.', '/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Wonder Woman', 'An Amazon princess comes to the world of Man in the grips of the First World War to confront the forces of evil and bring an end to human conflict.', '/imekS7f1OuHyUP2LAiTEM0zBzUz.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Thor: Ragnarok', 'Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the destruction of his home-world and the end of Asgardian civilization, at the hands of a powerful new threat, the ruthless Hela.', '/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Monkey Man', 'Kid is an anonymous young man who ekes out a meager living in an underground fight club where, night after night, wearing a gorilla mask, he is beaten bloody by more popular fighters for cash. After years of suppressed rage, Kid discovers a way to infiltrate the enclave of the city’s sinister elite. As his childhood trauma boils over, his mysteriously scarred hands unleash an explosive campaign of retribution to settle the score with the men who took everything from him.', '/4lhR4L2vzzjl68P1zJyCH755Oz4.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Land of Bad', 'When a Delta Force special ops mission goes terribly wrong, Air Force drone pilot Reaper has 48 hours to remedy what has devolved into a wild rescue operation. With no weapons and no communication other than the drone above, the ground mission suddenly becomes a full-scale battle when the team is discovered by the enemy.', '/h3jYanWMEJq6JJsCopy1h7cT2Hs.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Terminator', 'In the post-apocalyptic future, reigning tyrannical supercomputers teleport a cyborg assassin known as the "Terminator" back to 1984 to kill Sarah Connor, whose unborn son is destined to lead insurgents against 21st century mechanical hegemony. Meanwhile, the human-resistance movement dispatches a lone warrior to safeguard Sarah. Can he stop the virtually indestructible killing machine?', '/qvktm0BHcnmDpul4Hz01GIazWPr.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Logan', 'In the near future, a weary Logan cares for an ailing Professor X in a hideout on the Mexican border. But Logan''s attempts to hide from the world and his legacy are upended when a young mutant arrives, pursued by dark forces.', '/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Creation of the Gods I: Kingdom of Storms', 'Based on the most well-known classical fantasy novel of China, Fengshenyanyi, the trilogy is a magnificent eastern high fantasy epic that recreates the prolonged mythical wars between humans, immortals and monsters, which happened more than three thousand years ago.', '/ccJpK0rqzhQeP7Mrs2uKqObFY4L.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Star Wars', 'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.', '/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg', 5.00, 1, 'Adventure');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Matrix', 'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.', '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Flash', 'When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry''s only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?', '/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Bird Box', 'Five years after an ominous unseen presence drives most of society to suicide, a survivor and her two children make a desperate bid to reach safety.', '/rGfGfgL2pEPCfhIvqHXieXFn7gp.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Marvels', 'Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.', '/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Barbie', 'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.', '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg', 5.00, 1, 'Comedy');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Interstellar', 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.', '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', 5.00, 1, 'Adventure');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Iron Man 2', 'With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press and the public to share his technology with the military. Unwilling to let go of his invention, Stark, with Pepper Potts and James ''Rhodey'' Rhodes at his side, must forge new alliances – and confront powerful enemies.', '/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg', 5.00, 1, 'Adventure');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Black Panther', 'King T''Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country''s new leader. However, T''Challa soon finds that he is challenged for the throne by factions within his own country as well as without. Using powers reserved to Wakandan kings, T''Challa assumes the Black Panther mantle to join with ex-girlfriend Nakia, the queen-mother, his princess-kid sister, members of the Dora Milaje (the Wakandan ''special forces'') and an American secret agent, to prevent Wakanda from being dragged into a world war.', '/uxzzxijgPIY7slzFvMotPv8wjKA.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Wonka', 'Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.', '/qhb1qOilapbapxWQn9jtRCMwXJF.jpg', 5.00, 1, 'Comedy');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Abigail', 'After a group of would-be criminals kidnap the 12 year old ballerina daughter of a powerful underworld figure, all they have to do to collect a $50 million ransom is watch the girl overnight. In an isolated mansion, the captors start to dwindle, one by one, and they discover, to their mounting horror, that they’re locked inside with no normal little girl.', '/5Uq8P6MPj9Ppsns5t82AiCiUaWE.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Beekeeper', 'One man''s campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.', '/A7EByudX0eOzlkQ2FIbogzyazm2.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Misery', 'After stalking and saving the life of her favorite fiction author in a car accident, his  manic obsessor holds him captive in her remote Colorado home then forces him to write back to life the popular literary character he killed off.', '/23Y65uWaVMpqfbZTN3CT0aei4D5.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Serenity', 'When the renegade crew of Serenity agrees to hide a fugitive on their ship, they find themselves in an action-packed battle between the relentless military might of a totalitarian regime who will destroy anything – or anyone – to get the girl back and the bloodthirsty creatures who roam the uncharted areas of space. But... the greatest danger of all may be on their ship.', '/ckDo5vnRKehJ2qu8U95c7QcvGUm.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Alien', 'During its return to the earth, commercial spaceship Nostromo intercepts a distress signal from a distant planet. When a three-member team of the crew discovers a chamber containing thousands of eggs on the planet, a creature inside one of the eggs attacks an explorer. The entire crew is unaware of the impending nightmare set to descend upon them when the alien parasite planted inside its unfortunate host is birthed.', '/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Turning Red', 'Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.', '/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg', 5.00, 1, 'Animation');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Heart of the Hunter', 'A retired assassin is pulled back into action when his friend uncovers a dangerous conspiracy at the heart of the South African government.', '/n726fdyL1dGwt15bY7Nj3XOXc4Q.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Dark Phoenix', 'The X-Men face their most formidable and powerful foe when one of their own, Jean Grey, starts to spiral out of control. During a rescue mission in outer space, Jean is nearly killed when she''s hit by a mysterious cosmic force. Once she returns home, this force not only makes her infinitely more powerful, but far more unstable. The X-Men must now band together to save her soul and battle aliens that want to use Grey''s new abilities to rule the galaxy.', '/cCTJPelKGLhALq3r51A9uMonxKj.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Poor Things', 'Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.', '/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Spectre', 'A cryptic message from Bond’s past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.', '/zj8ongFhtWNsVlfjOGo8pSr7PQg.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), '2001: A Space Odyssey', 'Humanity finds a mysterious object buried beneath the lunar surface and sets off to find its origins with the help of HAL 9000, the world''s most advanced super computer.', '/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Tearsmith', 'Adopted together after a tough childhood in an orphanage, Nica and Rigel realize that unexpected but irresistible feelings pull them together.', '/uoBHsxSgfc3PQsSn98RfnbePHOy.jpg', 5.00, 1, 'Romance');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Deadpool 2', 'Wisecracking mercenary Deadpool battles the evil and powerful Cable and other bad guys to save a boy''s life.', '/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Love Lies Bleeding', 'Reclusive gym manager Lou falls hard for Jackie, an ambitious bodybuilder headed through town to Las Vegas in pursuit of her dream. But their love ignites violence, pulling them deep into the web of Lou’s criminal family.', '/p7jyFWiLyHPttqYBFAlLJwtYTYH.jpg', 5.00, 1, 'Crime');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Inception', 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person''s idea into a target''s subconscious.', '/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Rocky', 'An uneducated collector for a Philadelphia loan shark is given a once-in-a-lifetime opportunity to fight against the world heavyweight boxing champion.', '/cqxg1CihGR5ge0i1wYXr4Rdeppu.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Alien: Covenant', 'The crew of the colony ship Covenant, bound for a remote planet on the far side of the galaxy, discovers what they think is an uncharted paradise but is actually a dark, dangerous world.', '/zecMELPbU5YMQpC81Z8ImaaXuf9.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Morbius', 'Dangerously ill with a rare blood disorder, and determined to save others suffering his same fate, Dr. Michael Morbius attempts a desperate gamble. What at first appears to be a radical success soon reveals itself to be a remedy potentially worse than the disease.', '/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Donnie Darko', 'After narrowly escaping a bizarre accident, a troubled teenager is plagued by visions of a large bunny rabbit that manipulates him to commit a series of crimes.', '/fhQoQfejY1hUcwyuLgpBrYs6uFt.jpg', 5.00, 1, 'Fantasy');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Split', 'Though Kevin has evidenced 23 personalities to his trusted psychiatrist, Dr. Fletcher, there remains one still submerged who is set to materialize and dominate all the others. Compelled to abduct three teenage girls led by the willful, observant Casey, Kevin reaches a war for survival among all of those contained within him — as well as everyone around him — as the walls between his compartments shatter apart.', '/lli31lYTFpvxVBeFHWoe5PMfW5s.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Taxi Driver', 'A mentally unstable Vietnam War veteran works as a night-time taxi driver in New York City where the perceived decadence and sleaze feed his urge for violent action.', '/ekstpH614fwDX8DUln1a2Opz0N8.jpg', 5.00, 1, 'Crime');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Predator', 'A team of elite commandos on a secret mission in a Central American jungle come to find themselves hunted by an extraterrestrial warrior.', '/k3mW4qfJo6SKqe6laRyNGnbB9n5.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Halloween', 'Laurie Strode comes to her final confrontation with Michael Myers, the masked figure who has haunted her since she narrowly escaped his killing spree on Halloween night four decades ago.', '/f7JAX5EGk4GgsEnus6OxyzwpFp7.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Kate', 'A ruthless criminal operative has less than 24 hours to exact revenge on her enemies and in the process forms an unexpected bond with the daughter of one of her past victims.', '/uJgdT1boTSP0dDIjdTgGleg71l4.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Green Book', 'Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.', '/7BsvSuDQuoqhWmU2fL7W2GOcZHU.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Becoming', 'Join former first lady Michelle Obama in an intimate documentary looking at her life, hopes and connection with others.', '/f0vo1yoEVlbpJ0Fkn0FgU7dTrO8.jpg', 5.00, 1, 'Documentary');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Sri Asih', 'Alana discover the truth about her origin: she’s not an ordinary human being. She may be the gift for humanity and become its protector as Sri Asih. Or a destruction, if she can’t control her anger.', '/wShcJSKMFg1Dy1yq7kEZuay6pLS.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Wish', 'Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.', '/vgJZSqKMXWDDx09iSIStGKfHMku.jpg', 5.00, 1, 'Animation');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Doctor Strange', 'After his career is destroyed, a brilliant but arrogant surgeon gets a new lease on life when a sorcerer takes him under her wing and trains him to defend the world against evil.', '/7WfK17BXE6szXlm4WOxfswgbdsL.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Con Air', 'Newly-paroled former US Army ranger Cameron Poe is headed back to his wife, but must fly home aboard a prison transport flight dubbed "Jailbird" taking the “worst of the worst” prisoners, a group described as “pure predators”, to a new super-prison. Poe faces impossible odds when the transport plane is skyjacked mid-flight by the most vicious criminals in the country led by the mastermind — genius serial killer Cyrus "The Virus" Grissom, and backed by black militant Diamond Dog and psychopath Billy Bedlam.', '/kOKjgrEzGOP92rVQ6srA9jtp60l.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Gravity', 'Dr. Ryan Stone, a brilliant medical engineer on her first Shuttle mission, with veteran astronaut Matt Kowalsky in command of his last flight before retiring. But on a seemingly routine spacewalk, disaster strikes. The Shuttle is destroyed, leaving Stone and Kowalsky completely alone-tethered to nothing but each other and spiraling out into the blackness of space. The deafening silence tells them they have lost any link to Earth and any chance for rescue. As fear turns to panic, every gulp of air eats away at what little oxygen is left. But the only way home may be to go further out into the terrifying expanse of space.', '/kZ2nZw8D681aphje8NJi8EfbL1U.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'You''ll Never Find Me', 'Patrick, a strange and lonely resident, lives in a mobile home at the back of an isolated caravan park. After a violent thunderstorm erupts, a mysterious young woman appears at his door, seeking shelter from the weather. The longer the night wears on and the more the young woman discovers about Patrick, the more difficult she finds it to leave. Soon she begins to question Patrick’s intentions, while Patrick begins to question his own grip on reality...', '/jdDrzkq1vgQzR6vZPumyjHiKvFP.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'RoboCop', 'In a violent, near-apocalyptic Detroit, evil corporation Omni Consumer Products wins a contract from the city government to privatize the police force. To test their crime-eradicating cyborgs, the company leads street cop Alex Murphy into an armed confrontation with crime lord Boddicker so they can use his body to support their untested RoboCop prototype. But when RoboCop learns of the company''s nefarious plans, he turns on his masters.', '/hHtOgGb3NihlyRATHlKPaFApbrd.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Deadpool & Wolverine', 'Third entry in the "Deadpool" franchise. Plot TBA.', '/ajnzOECvXpa7VcVx0RSlq39XgHe.jpg', 5.00, 1, 'Comedy');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Superman', 'Mild-mannered Clark Kent works as a reporter at the Daily Planet alongside his crush, Lois Lane. Clark must summon his superhero alter-ego when the nefarious Lex Luthor launches a plan to take over the world.', '/d7px1FQxW4tngdACVRsCSaZq0Xl.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Mercy Falls', 'A group of friends set off into the Scottish Highlands in search of a long lost cabin. Once far from civilization, an unforeseen tragedy befalls the group and one bad decision leads to suspicion, betrayal and murder.', '/aNiAEjTebmwJtTx95SQzW9ZXUdf.jpg', 5.00, 1, 'Thriller');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The First Omen', 'When a young American woman is sent to Rome to begin a life of service to the church, she encounters a darkness that causes her to question her own faith and uncovers a terrifying conspiracy that hopes to bring about the birth of evil incarnate.', '/phUZyA2TVWuS3Kn6Vdokh8HoIYW.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Arrival', 'Taking place after alien crafts land around the world, an expert linguist is recruited by the military to determine whether they come in peace or are a threat.', '/pEzNVQfdzYDzVK0XqxERIw2x2se.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Vikings: Battle of Heirs', 'A young Viking must come to terms with the realization that he may be the King''s son, who was switched at birth, but not before others try to take his rightful place.', '/87goLbbqrJqAxqDS5cBsik1zKT.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Exhuma', 'After tracing the origin of a disturbing supernatural affliction to a wealthy family''s ancestral gravesite, a team of paranormal experts relocates the remains—and soon discovers what happens to those who dare to mess with the wrong grave.', '/pQYHouPsDw32FhDLr7E3jmw0WTk.jpg', 5.00, 1, 'Mystery');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Baywatch', 'Devoted lifeguard Mitch Buchannon butts heads with a brash new recruit. Together, they uncover a local criminal plot that threatens the future of the Bay.', '/6HE4xd8zloDqmjMZuhUCCw2UcY1.jpg', 5.00, 1, 'Comedy');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Dark City', 'A man struggles with memories of his past, including a wife he cannot remember, in a nightmarish world with no sun and run by beings with telekinetic powers who seek the souls of humans.', '/AdBe2ow8hdlT2aLBYuUjs0Xkqkw.jpg', 5.00, 1, 'Mystery');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Aquaman', 'Half-human, half-Atlantean Arthur Curry is taken on the journey of his lifetime to discover if he is worth of being a king.', '/zdw7Wf97vsQ0YnGomxDqfcEdUjX.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Aquaman', 'Half-human, half-Atlantean Arthur Curry is taken on the journey of his lifetime to discover if he is worth of being a king.', '/zdw7Wf97vsQ0YnGomxDqfcEdUjX.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'xXx', 'Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government "recruits" him to go on a mission, he''s not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.', '/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Scarface', 'After getting a green card in exchange for assassinating a Cuban government official, Tony Montana stakes a claim on the drug trade in Miami. Viciously murdering anyone who stands in his way, Tony eventually becomes the biggest drug lord in the state, controlling nearly all the cocaine that comes through Miami. But increased pressure from the police, wars with Colombian drug cartels and his own drug-fueled paranoia serve to fuel the flames of his eventual downfall.', '/iQ5ztdjvteGeboxtmRdXEChJOHh.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Baghead', 'Following the death of her estranged father, Iris learns she has inherited a run-down, centuries-old pub. She travels to Berlin to identify her father’s body and meet with The Solicitor to discuss the estate. Little does she know, when the deed is signed she will become inextricably tied to an unspeakable entity that resides in the pub’s basement – Baghead – a shape-shifting creature that can transform into the dead.', '/lbOyeiiRYAE6Nm2e7xiNAAaRwZB.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Megamind vs. the Doom Syndicate', 'Megamind''s former villain team, The Doom Syndicate, has returned. Our newly crowned blue hero must now keep up evil appearances until he can assemble his friends (Roxanne, Ol'' Chum and Keiko) to stop his former evil teammates from launching Metro City to the Moon.', '/1N7terrMeZPwK5qq31MUD0HQ3IG.jpg', 5.00, 1, 'Animation');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Ghostbusters: Frozen Empire', 'The Spengler family returns to where it all started – the iconic New York City firehouse – to team up with the original Ghostbusters, who''ve developed a top-secret research lab to take busting ghosts to the next level. But when the discovery of an ancient artifact unleashes an evil force, Ghostbusters new and old must join forces to protect their home and save the world from a second Ice Age.', '/6faYaQyiBPhqAizldJKq21mIVaE.jpg', 5.00, 1, 'Fantasy');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Venom', 'Investigative journalist Eddie Brock attempts a comeback following a scandal, but accidentally becomes the host of Venom, a violent, super powerful alien symbiote. Soon, he must rely on his newfound powers to protect the world from a shadowy organization looking for a symbiote of their own.', '/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Gifted', 'Frank, a single man raising his child prodigy niece Mary, is drawn into a custody battle with his mother.', '/7YB2YrMwIm1g8FyZtlvmVDfRnAT.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Death Wish', 'A mild-mannered father is transformed into a killing machine after his family is torn apart by a violent act.', '/g0eEEZAqMf98ULQnoiORuazjOpn.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Blade', 'A film set in the Marvel Cinematic Universe (MCU) based on the Marvel Comics character of the same name.', '/fKqA4rgVJwrM7Gb3tQ9TGHnu8Tr.jpg', 5.00, 1, 'Fantasy');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Dawn of the Planet of the Apes', 'A group of scientists in San Francisco struggle to stay alive in the aftermath of a plague that is wiping out humanity, while Caesar tries to maintain dominance over his community of intelligent apes.', '/kScdQEwS9jPEdnO23XjGAtaoRcT.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Fall Guy', 'Fresh off an almost career-ending accident, stuntman Colt Seavers has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job.', '/e7olqFmzcIX5c23kX4zSmLPJi8c.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Pulp Fiction', 'A burger-loving hit man, his philosophical partner, a drug-addled gangster''s moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.', '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg', 5.00, 1, 'Thriller');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Avengers: Infinity War', 'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.', '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg', 5.00, 1, 'Adventure');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Jade', 'Jade presents the story of a woman who comes between a powerful businessman and a gang leader in their search for a hard drive that could damage the operations of Interpol. Despite grieving for the brother she accidentally killed, the woman is required to use her unique set of skills to retrieve the drive and protect her brother''s unborn child being carried by another woman.', '/pqotEkHRbhUPUuX9Gq4U6aJzK55.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Judge Dredd', 'In a dystopian future, Dredd, the most famous judge (a cop with instant field judiciary powers) is convicted for a crime he did not commit while his murderous counterpart escapes.', '/cfSnKn8NDU3m8UxihjVcYprA0Aq.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Silence', 'Two Jesuit priests travel to seventeenth century Japan which has, under the Tokugawa shogunate, banned Catholicism and almost all foreign contact.', '/x5T0cQDYws0xRBVG4Q3wpcrcmax.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Anyone But You', 'After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.', '/5qHoazZiaLe7oFBok7XlUhg96f2.jpg', 5.00, 1, 'Romance');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Justice League', 'Fuelled by his restored faith in humanity and inspired by Superman''s selfless act, Bruce Wayne and Diana Prince assemble a team of metahumans consisting of Barry Allen, Arthur Curry and Victor Stone to face the catastrophic threat of Steppenwolf and the Parademons who are on the hunt for three Mother Boxes on Earth.', '/eifGNCSDuxJeS1loAXil5bIGgvC.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Citizen Kane', 'Newspaper magnate Charles Foster Kane is taken from his mother as a boy and made the ward of a rich industrialist. As a result, every well-meaning, tyrannical or self-destructive move he makes for the rest of his life appears in some way to be a reaction to that deeply wounding event.', '/sav0jxhqiH0bPr2vZFU0Kjt2nZL.jpg', 5.00, 1, 'Mystery');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Roommate', 'Vivi is a young writer who is forced to find a roommate to pay the mortgage on her apartment. What she does not suspect is that Roy, the supposed perfect partner she found, has a peculiar lifestyle: he never pays rent.', '/zaRzz2BxjxIVb7ja0gSedj1Hn1E.jpg', 5.00, 1, 'Comedy');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), '578: Magnum', 'A container truck driver, Hùng, lives an idyllic life with his little daughter, An. The father and daughter become the closest companions in every journey with their orange container truck. Life goes on like that until An has to leave her father to go to school. One day, Hùng is informed that An is suffering from severe depression. Relying on his old skills in the past and finding out the truth, Hùng becomes enraged and painful to know that his little girl was kidnapped by a male stranger. Starting his lone and intense journey looking for and chasing after the unknown abuser, Hùng realizes that to hunt down that psychopath he has to counter the massive underground forces behind him.', '/8Nw5v7wPfa2FwbKyx61K2nIBcKa.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Adventures of Maid Marian', 'Everyone knows the stories of Robin Hood and Maid Marian, but this the story of what happens next. Out of the shadows, a legend returns to save her people from the tyranny of the disgraced Sheriff of Nottingham. Robin Hood remains at war and Marian must put her own combat skills to the test, creating a new tale that will be heralded throughout the ages.', '/oPXzCV01ysDmnmpJOkiVqaZQ5QR.jpg', 5.00, 1, 'Adventure');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Total Recall', 'Factory worker Doug Quaid takes a virtual mind-trip vacation with the Rekall company, opting for implanted memories of being a spy. When the procedure goes wrong, Quaid becomes a wanted man by the police and joins forces with a rebel fighter to stop the evil Chancellor Cohaagen.', '/4M5urSlUyR2PtVBIoW9hLG9NQCQ.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Babylon', 'A tale of outsized ambition and outrageous excess, tracing the rise and fall of multiple characters in an era of unbridled decadence and depravity during Hollywood''s transition from silent films to sound films in the late 1920s.', '/wjOHjWCUE0YzDiEzKv8AfqHj3ir.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Creepshow', 'Five tales in the style of classic ''50s horror comics, involving a murdered man emerging from the grave, a meteor''s ooze that makes everything grow, a snack for a crated creature, a scheming husband, and a malevolent millionaire with an insect phobia.', '/4SoyTCEpsgLjX6yAyMsx3AsAyRQ.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Angel Heart', 'Harry Angel, a down-and-out Brooklyn detective, is hired to track down a singer on an odyssey that will take him through the desperate streets of Harlem, the smoke-filled jazz clubs of New Orleans, and the swamps of Louisiana and its seedy underworld of voodoo.', '/h5v3wjJQNB7q2RntEnKDLhKtTFE.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Logan Lucky', 'Trying to reverse a family curse, brothers Jimmy and Clyde Logan set out to execute an elaborate robbery during the legendary Coca-Cola 600 race at the Charlotte Motor Speedway.', '/mQrhrBaaHvRfBQq0Px3HtVbH9iE.jpg', 5.00, 1, 'Comedy');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Void', 'In the middle of a routine patrol, officer Daniel Carter happens upon a blood-soaked figure limping down a deserted stretch of road. He rushes the young man to a nearby rural hospital staffed by a skeleton crew, only to discover that patients and personnel are transforming into something inhuman. As the horror intensifies, Carter leads the other survivors on a hellish voyage into the subterranean depths of the hospital in a desperate bid to end the nightmare before it''s too late.', '/c0WLRyT0AmUi41nVXBnqmJshIBn.jpg', 5.00, 1, 'Mystery');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Garfield Movie', 'Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.', '/zK2sFxZcelHJRPVr242rxy5VK4T.jpg', 5.00, 1, 'Animation');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Baby Driver', 'After being coerced into working for a crime boss, a young getaway driver finds himself taking part in a heist doomed to fail.', '/rmnQ9jKW72bHu8uKlMjPIb2VLMI.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Argylle', 'When the plots of reclusive author Elly Conway''s fictional espionage novels begin to mirror the covert actions of a real-life spy organization, quiet evenings at home become a thing of the past. Accompanied by her cat Alfie and Aiden, a cat-allergic spy, Elly races across the world to stay one step ahead of the killers as the line between Conway''s fictional world and her real one begins to blur.', '/siduVKgOnABO4WH4lOwPQwaGwJp.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Omen', 'Immediately after their miscarriage, the US diplomat Robert Thorn adopts the newborn Damien without the knowledge of his wife. Yet what he doesn’t know is that their new son is the son of the devil.', '/p0LcWxOIoBx0MEZMn8tFcrvDXR1.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Transformers: Rise of the Beasts', 'When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.', '/gPbM0MK8CP8A174rmUwGsADNYKD.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Code 8 Part II', 'In a world where superpowered people are heavily policed by robots, an ex-con teams up with a drug lord he despises to protect a teen from a corrupt cop.', '/hhvMTxlTZtnCOe7YFhod9uz3m37.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Hunters', 'As John T. Wrecker continues his task of protecting a group of refugees from a virus, the threat of something new and even more dangerous grows ever closer in the form of monstrous mutants.', '/3UKlVa1CBeQkRksHV5OfFTO52qd.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Skal - Fight for Survival', 'My name''s Arthur, a huge Internet star who''s just hit 3 million subs. While in the midst of throwing an epic party to celebrate, the universe had the balls to bring on the effing apocalypse and cut my night short. What was supposed to be a perfect hangover, has turned into an epic fight for survival.', '/1On8iF3AsFIbpyfZg1xiGWMAFBn.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Ghostbusters', 'After losing their academic posts at a prestigious university, a team of parapsychologists goes into business as proton-pack-toting "ghostbusters" who exterminate ghouls, hobgoblins and supernatural pests of all stripes. An ad campaign pays off when a knockout cellist hires the squad to purge her swanky digs of demons that appear to be living in her refrigerator.', '/7E8nLijS9AwwUEPu2oFYOVKhdFA.jpg', 5.00, 1, 'Comedy');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Imaginary', 'When Jessica moves back into her childhood home with her family, her youngest stepdaughter Alice develops an eerie attachment to a stuffed bear named Chauncey she finds in the basement. Alice starts playing games with Chauncey that begin playful and become increasingly sinister. As Alice’s behavior becomes more and more concerning, Jessica intervenes only to realize Chauncey is much more than the stuffed toy bear she believed him to be.', '/9u6HEtZJdZDjPGGJq6YEuhPnoan.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Godzilla Minus One', 'Postwar Japan is at its lowest point when a new crisis emerges in the form of a giant monster, baptized in the horrific power of the atomic bomb.', '/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Toy Story', 'Led by Woody, Andy''s toys live happily in his room until Andy''s birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy''s heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.', '/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg', 5.00, 1, 'Animation');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Se7en', 'Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer''s mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.', '/6yoghtyTpznpBik8EngEmJskVUO.jpg', 5.00, 1, 'Crime');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Super Mario Bros. Movie', 'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.', '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg', 5.00, 1, 'Animation');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Prey', 'When danger threatens her camp, the fierce and highly skilled Comanche warrior Naru sets out to protect her people. But the prey she stalks turns out to be a highly evolved alien predator with a technically advanced arsenal.', '/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg', 5.00, 1, 'Thriller');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Lady Bird', 'Lady Bird McPherson, a strong willed, deeply opinionated, artistic 17 year old comes of age in Sacramento. Her relationship with her mother and her upbringing are questioned and tested as she plans to head off to college.', '/gl66K7zRdtNYGrxyS2YDUP5ASZd.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Inside Out 2', 'Teenager Riley''s mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.', '/xeqXXTE1Cd3qNaAEOT6qbhhCsgJ.jpg', 5.00, 1, 'Animation');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Puppy Love', 'After a disastrous first date, wild-child Nicole and socially-anxious Max vow to lose each other’s numbers until they learn that their dogs found a love match, and now puppies are on the way! The hilariously mismatched Nicole and Max are forced to become responsible co-parents, but may end up finding love themselves.', '/oTc03izWZ9UdD3y0HegVV2M0s0J.jpg', 5.00, 1, 'Comedy');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Swapping: Perfect Neighbor', 'Couple Jin-goo and Joo-hee have been experiencing a lover''s slump after their marriage. Meanwhile, a new couple in the neighborhood, Hyun-jin and Yoo-jeong came to the other couple''s house to introduce themselves. They''re attracted with each other''s husbands and wives, and in the end, crosses the line that is not supposed to be crossed within neighbors. After that day, two couples'' passion intensifies...', '/3ArCpGHdnVqBjhkdRcQHSBYH1yA.jpg', 5.00, 1, 'Romance');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'GoodFellas', 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.', '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Freelance', 'An ex-special forces operative takes a job to provide security for a journalist as she interviews a dictator, but a military coup breaks out in the middle of the interview, they are forced to escape into the jungle where they must survive.', '/7Bd4EUOqQDKZXA6Od5gkfzRNb0.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Avengers: Endgame', 'After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos'' actions and restore order to the universe once and for all, no matter what consequences may be in store.', '/or06FN3Dka5tukK1e9sl16pB3iy.jpg', 5.00, 1, 'Adventure');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Spider-Man: No Way Home', 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.', '/5weKu49pzJCt06OPpjvT80efnQj.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Infested', 'Residents of a rundown French apartment building battle against an army of deadly, rapidly reproducing spiders.', '/dY98PkUAbIGUUg0FhXEcOkbzHIZ.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Blade', 'The Daywalker known as "Blade" - a half-vampire, half-mortal man - becomes the protector of humanity against an underground army of vampires.', '/oWT70TvbsmQaqyphCZpsnQR7R32.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Meteor', 'After a meteor collides into Earth, a lonely rancher and a lost young girl are on the run from vicious mercenaries.', '/tVMddOS5bi3YPVPgTPlEw0TOWoF.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'My Fault', 'Noah must leave her city, boyfriend, and friends to move into William Leister''s mansion, the flashy and wealthy husband of her mother Rafaela. As a proud and independent 17 year old, Noah resists living in a mansion surrounded by luxury. However, it is there where she meets Nick, her new stepbrother, and the clash of their strong personalities becomes evident from the very beginning.', '/w46Vw536HwNnEzOa7J24YH9DPRS.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Avatar: The Way of Water', 'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.', '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Skyscraper', 'Framed and on the run, a former FBI agent must save his family from a blazing fire in the world''s tallest building.', '/52ml62vClzrlqvXZq2FEW6UF6c1.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Grease', 'Australian good girl Sandy and greaser Danny fell in love over the summer. But when they unexpectedly discover they''re now in the same high school, will they be able to rekindle their romance despite their eccentric friends?', '/czVhhAaSBFpakur7U8pOIDV9NUG.jpg', 5.00, 1, 'Romance');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Help', 'Aibileen Clark is a middle-aged African-American maid who has spent her life raising white children and has recently lost her only son; Minny Jackson is an African-American maid who has often offended her employers despite her family''s struggles with money and her desperate need for jobs; and Eugenia "Skeeter" Phelan is a young white woman who has recently moved back home after graduating college to find out her childhood maid has mysteriously disappeared. These three stories intertwine to explain how life in Jackson, Mississippi revolves around "the help"; yet they are always kept at a certain distance because of racial lines.', '/7XLSwxpfpPoJyTdJVot6a42TS2V.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Aquaman and the Lost Kingdom', 'Black Manta seeks revenge on Aquaman for his father''s death. Wielding the Black Trident''s power, he becomes a formidable foe. To defend Atlantis, Aquaman forges an alliance with his imprisoned brother. They must protect the kingdom.', '/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Stand by Me', 'After learning that a boy their age has been accidentally killed near their rural homes, four Oregon boys decide to go see the body. On the way, Gordie,  Vern, Chris and Teddy encounter a mean junk man and a marsh full of leeches, as they also learn more about one another and their very different home lives. Just a lark at first, the boys'' adventure evolves into a defining event in their lives.', '/vz0w9BSehcqjDcJOjRaCk7fgJe7.jpg', 5.00, 1, 'Crime');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Shazam!', 'A boy is given the ability to become an adult superhero in times of need with a single magic word.', '/xnopI5Xtky18MPhK40cZAGAOVeV.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Chappie', 'Every child comes into the world full of promise, and none more so than Chappie: he is gifted, special, a prodigy. Like any child, Chappie will come under the influence of his surroundings—some good, some bad—and he will rely on his heart and soul to find his way in the world and become his own man. But there''s one thing that makes Chappie different from any one else: he is a robot.', '/hpnuXlKKWznTgbheGe4iQXzkuwJ.jpg', 5.00, 1, 'Crime');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Allied', 'In 1942, an intelligence officer in North Africa encounters a female French Resistance fighter on a deadly mission behind enemy lines. When they reunite in London, their relationship is tested by the pressures of war.', '/sV4lXM32quwminL3TP36nlNPp7Q.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Inside Out', 'From an adventurous balloon ride above the clouds to a monster-filled metropolis, Academy Award®-winning director Pete Docter (“Monsters, Inc.,” “Up”) has taken audiences to unique and imaginative places. In Disney and Pixar’s original movie “ Inside Out,” he will take us to the most extraordinary location of all—inside the mind.', '/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg', 5.00, 1, 'Animation');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Godzilla vs. Kong', 'In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.', '/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Species', 'In 1993, the Search for Extra Terrestrial Intelligence Project receives a transmission detailing an alien DNA structure, along with instructions on how to splice it with human DNA. The result is Sil, a sensual but deadly creature who can change from a beautiful woman to an armour-plated killing machine in the blink of an eye.', '/cT5wdyo8kT7dycqjrolJ2sHWkFx.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Creed II', 'Between personal obligations and training for his next big fight against an opponent with ties to his family''s past, Adonis Creed is up against the challenge of his life.', '/v3QyboWRoA4O9RbcsqH8tJMe8EB.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Nobody', 'Hutch Mansell, a suburban dad, overlooked husband, nothing neighbor — a "nobody." When two thieves break into his home one night, Hutch''s unknown long-simmering rage is ignited and propels him on a brutal path that will uncover dark secrets he fought to leave behind.', '/oBgWY00bEFeZ9N25wWVyuQddbAo.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Downsizing', 'A kindly occupational therapist undergoes a new procedure to be shrunken to four inches tall so that he and his wife can help save the planet and afford a nice lifestyle at the same time.', '/5bNzInSSAXfr0MFlHfb4IoQePVx.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Rings', 'Julia becomes worried about her boyfriend Holt when he explores the dark urban legend of a mysterious videotape said to kill the watcher seven days after viewing. She sacrifices herself to save her boyfriend and in doing so makes a horrifying discovery: there is a "movie within the movie" that no one has ever seen before.', '/5FoczK6tDFzC9OyHiMMNIeNspek.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Creed III', 'After dominating the boxing world, Adonis Creed has thrived in his career and family life. When a childhood friend and former boxing prodigy, Damian Anderson, resurfaces after serving a long sentence in prison, he is eager to prove that he deserves his shot in the ring. The face-off between former friends is more than just a fight. To settle the score, Adonis must put his future on the line to battle Damian — a fighter with nothing to lose.', '/cvsXj3I9Q2iyyIo95AecSd1tad7.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Black Adam', 'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.', '/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Spider-Man: Homecoming', 'Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.', '/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Mummy', 'Though safely entombed in a crypt deep beneath the unforgiving desert, an ancient queen whose destiny was unjustly taken from her is awakened in our current day, bringing with her malevolence grown over millennia, and terrors that defy human comprehension.', '/zxkY8byBnCsXodEYpK8tmwEGXBI.jpg', 5.00, 1, 'Fantasy');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Creator', 'Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.', '/vBZ0qvaRxqEhZwl6LWmruJqWE8Z.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Chinatown', 'Private eye Jake Gittes lives off of the murky moral climate of sunbaked, pre-World War II Southern California. Hired by a beautiful socialite to investigate her husband''s extra-marital affair, Gittes is swept into a maelstrom of double dealings and deadly deceits, uncovering a web of personal and political scandals that come crashing together.', '/mQJz8J4naOA7RmCtypTPjgXZIMY.jpg', 5.00, 1, 'Crime');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Abyss', 'A civilian oil rig crew is recruited to conduct a search and rescue effort when a nuclear submarine mysteriously sinks. One diver soon finds himself on a spectacular odyssey 25,000 feet below the ocean''s surface where he confronts a mysterious force that has the power to change the world or destroy it.', '/8NMEf8D2v85bQ6VNvexTqI9tVvG.jpg', 5.00, 1, 'Adventure');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Tarot', 'When a group of friends recklessly violates the sacred rule of Tarot readings they unknowingly unleash an unspeakable evil trapped within the cursed cards. One by one, they come face to face with fate and end up in a race against death.', '/gAEUXC37vl1SnM7PXsHTF23I2vq.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'War for the Planet of the Apes', 'Caesar and his apes are forced into a deadly conflict with an army of humans led by a ruthless Colonel. After the apes suffer unimaginable losses, Caesar wrestles with his darker instincts and begins his own mythic quest to avenge his kind. As the journey finally brings them face to face, Caesar and the Colonel are pitted against each other in an epic battle that will determine the fate of both their species and the future of the planet.', '/mMA1qhBFgZX8O36qPPTC016kQl1.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Lion King', 'Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny. But not everyone in the kingdom celebrates the new cub''s arrival. Scar, Mufasa''s brother—and former heir to the throne—has plans of his own. The battle for Pride Rock is ravaged with betrayal, tragedy and drama, ultimately resulting in Simba''s exile. With help from a curious pair of newfound friends, Simba will have to figure out how to grow up and take back what is rightfully his.', '/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg', 5.00, 1, 'Adventure');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Elemental', 'In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.', '/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg', 5.00, 1, 'Animation');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Titanic', '101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic''s departure through to its death—on its first and last voyage—on April 15, 1912.', '/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Jaws', 'When the seaside community of Amity finds itself under attack by a dangerous great white shark, the town''s chief of police, a young marine biologist, and a grizzled hunter embark on a desperate quest to destroy the beast before it strikes again.', '/lxM6kqilAdpdhqUl2biYp5frUxE.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The Nun', 'A priest with a haunted past and a novice on the threshold of her final vows are sent by the Vatican to investigate the death of a young nun in Romania and confront a malevolent force in the form of a demonic nun.', '/sFC1ElvoKGdHJIWRpNB3xWJ9lJA.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Rebel Moon - Part One: A Child of Fire', 'When the ruthless forces of the Motherworld threaten a quiet farming village on a distant moon, a mysterious outsider becomes its best hope for survival.', '/ui4DrH1cKk2vkHshcUcGt2lKxCm.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Saw X', 'Between the events of ''Saw'' and ''Saw II'', a sick and desperate John Kramer travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer, only to discover the entire operation is a scam to defraud the most vulnerable. Armed with a newfound purpose, the infamous serial killer returns to his work, turning the tables on the con artists in his signature visceral way through devious, deranged, and ingenious traps.', '/aQPeznSu7XDTrrdCtT5eLiu52Yu.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Ricky Stanicky', 'When three childhood best friends pull a prank gone wrong, they invent the imaginary Ricky Stanicky to get them out of trouble. Twenty years later, the trio still uses the nonexistent Ricky as a handy alibi for their immature behavior. But when their spouses and partners get suspicious and demand to finally meet the fabled Mr. Stanicky, the guilty trio decide to hire a washed-up actor and raunchy celebrity impersonator to bring him to life.', '/cEuX73Q1wpMypB1cr4l3MoMGpL4.jpg', 5.00, 1, 'Comedy');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Get Out', 'Chris and his girlfriend Rose go upstate to visit her parents for the weekend. At first, Chris reads the family''s overly accommodating behavior as nervous attempts to deal with their daughter''s interracial relationship, but as the weekend progresses, a series of increasingly disturbing discoveries lead him to a truth that he never could have imagined.', '/mE24wUCfjK8AoBBjaMjho7Rczr7.jpg', 5.00, 1, 'Mystery');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Expend4bles', 'Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.', '/iwsMu0ehRPbtaSxqiaUDQB9qMWT.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Fight Club', 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.', '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', 5.00, 1, 'Drama');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Spider-Man: Across the Spider-Verse', 'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.', '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg', 5.00, 1, 'Animation');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'City Hunter', 'An exceptional marksman and hopeless playboy, private eye Ryo Saeba reluctantly forms an alliance with his late partner''s sister to investigate his death.', '/cjQzJ9xFdaN9KAwu7HUImIgbc2Y.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Predators', 'A group of cold-blooded killers find themselves trapped on an alien planet to be hunted by extraterrestrial Predators.', '/54LZIRznS0Zjn7ZDXrsGVe3HXei.jpg', 5.00, 1, 'Science Fiction');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Black Panther: Wakanda Forever', 'Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.', '/sv1xJUazXeYqALzczSZ3O6nkH75.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Black Widow', 'Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.', '/kwB7d51AIcyzPOBOHLCEZJkmPhQ.jpg', 5.00, 1, 'Action');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'The OctoGames', 'Eight contestants compete in eight deadly, classic children''s games. They seek fame beyond their wildest dreams, competing for the chance to take over the YouTube channel of the famous yet elusive masked content creator known only as "JaxPro".', '/qGz5rffXhegQH5PGUDiObqoOt06.jpg', 5.00, 1, 'Thriller');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Halloween', 'Fifteen years after murdering his sister on Halloween Night 1963, Michael Myers escapes from a mental hospital and returns to the small town of Haddonfield, Illinois to kill again.', '/wijlZ3HaYMvlDTPqJoTCWKFkCPU.jpg', 5.00, 1, 'Horror');
INSERT INTO vhs_tapes (id, title, description, img_url, price_per_day, quantity_available, genre) VALUES
      (UUID(), 'Scream 2', 'Away at college, Sidney Prescott thought she''d finally put the shocking murders that shattered her life behind her... until a copycat killer begins acting out a real-life sequel.', '/dORlVasiaDkJXTqt9bdH7nFNs6C.jpg', 5.00, 1, 'Horror');